### ISSUE TITLE
TS-653a Compatibility

### ISSUE THREAD

**Issue by EmAnzi3** [colinodell/python-qnapstats#45]
Please provide the following information along with your issue report (replace anything inside of `<>`):

**Device Model Number**: `TS-653a`

**QTS Version**: `4.5.1.1540`

Hello,

I tried to get the stats in Home Assistant from my Qnap TS-653a but without success.

This is what I applied to `configuration.yaml`:

```
sensor:
  - platform: qnap
    host: (myip)
    port: (myport)
    username: (myusername)
    password: (mypassword)
    verify_ssl: false
    monitored_conditions:
      - status
      - cpu_usage
      - memory_percent_used
      - network_tx
      - volume_percentage_used
```

Is anything I can do? Thanks
